# Generated by Django 2.0.4 on 2018-04-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API_Keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('key', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'keys',
            },
        ),
        migrations.CreateModel(
            name='Items_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('category', models.CharField(max_length=15)),
                ('dataset', models.CharField(max_length=10)),
                ('symbol', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
    ]
