# Generated by Django 2.0.4 on 2018-04-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quandl_chart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_keys',
            name='key',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='items_table',
            name='category',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
