# Generated by Django 2.0.4 on 2018-04-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quandl_chart', '0004_auto_20180417_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='items_table',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='items_table',
            name='subcategory',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='items_table',
            name='category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
