# Generated by Django 2.0.4 on 2018-04-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quandl_chart', '0005_auto_20180423_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='items_table',
            name='ccode',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
