# Generated by Django 2.0.5 on 2018-05-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quandl_chart', '0007_auto_20180423_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items_table',
            name='symbol',
            field=models.CharField(max_length=30),
        ),
    ]
